name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@feature/matrix-testing
    with:
      dotnet-logging: ${{ inputs.dotnet-logging }}
      dotnet-testfilter: "'UnitTest','IntegrationTest'"
      dotnet-version: 7.x
      solution: ./Http.Correlation.sln
    secrets: inherit
